#!/usr/bin/env bash
# Installs and configure HAproxy on a new ubuntu machine

sudo apt -y update
sudo apt -y install haproxy
sudo service haproxy start
sudo sed -i -e '$a\\nbackend backend-servers\n\tbalance roundrobin\n\tserver web-01 54.83.130.19:80 check\n\tserver web-02 54.146.90.129:80 check' /etc/haproxy/haproxy.cfg
sudo sed -i -e '$a\\nfrontend http\n\tbind *:80\n\tmode http\n\n\tacl index path_beg \/\n\tdefault_backend backend-servers\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart


