#!/usr/bin/env bash
# A script that displays Best School 10 times and hi after the 9th using while and if

n=1

while [ $n -le 10 ]

do 

	echo "Best School"

		if [ $n -eq 9 ]


		then
		
			echo -e "Hi"
		fi
	
	((n++))

done

